language: python
sudo: false
python:
        - "2.7"
install:
        - pip install -r req.txt
script:
        - ./manage.py makemigrations
        - ./manage.py migrate
        - ./manage.py test app
