language: python
sudo: false
python:
        - "2.7"
install:
        - pip install -r requirements.txt
script:
        - ./patches/apply.sh
        - ./manage.py makemigrations
        - ./manage.py migrate
        - ./manage.py test app
