nguage: python
python:
        - "2.7"
        - "3.4"
env:
        - DJANGO=1.2.7
        - DJANGO=1.3.1
        - DJANGO=1.4
install:
        - pip install -q Django==$DJANGO 
script:
        - python setup.py test
