web:
  build: .
  # Perhaps it's not the best location to compile the messages here
  command: bash -c "(cd app; django-admin compilemessages); python manage.py runserver 0.0.0.0:8000"
  volumes:
    - .:/code
  ports:
    - "8000:8000"
